name: Master
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: repo
      name: repo-checkout
      uses: actions/checkout@v3

    - id: python
      name: Python Setup & Package Install
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - id: jupyter
      name: notebook-exec
      run: jupyter execute scraping.ipynb & jupyter execute showtimes.ipynb
      shell: bash
